module.exports = [
    {
        "id": 1,
        "name": "Smárabíó",
        "website": "http://www.smarabio.is",
        "location": "Smáralind",
        "city": "201 Kópavogur",
        "phone": "564-0000",
        "image": "http://kvikmyndir.is/images/biohus_biosida/smarabio.jpg",
        "description": "Smárabíó er eitt fullkomnasta kvikmyndahús landsins.&lt;br&gt;&lt;br&gt;\r\n\r\nBíóið er með 5 sali og tekur rúmlega 1.000 manns í sæti..\r\n&lt;br&gt;&lt;br&gt;&lt;b&gt;\r\n\r\nVerð á bíómiðum&lt;/b&gt;:&lt;br&gt;\r\nAlmennt: 1100kr&lt;br&gt;\r\nÖryrkjar og eldriborgarar: 800kr&lt;br&gt;\r\nBörn yngri en 8 ára: 600kr&lt;br&gt;\r\nLúxus: 2100kr&lt;br&gt;\r\nTilbiðsbíó um helgar: 550kr (valdar sýningar)&lt;br&gt;\r\nAlmennt verð á 3D: 1350kr&lt;br&gt;\r\nBörn 8 ára og yngri á 3D: 850kr&lt;br&gt;\r\nÞriðjudagstilboð: 500kr (allar myndir nema í lúxus)&lt;br&gt;",
    },
    {
        "id": 2,
        "name": "Háskólabíó",
        "website": "http://www.haskolabio.is",
        "location": "Hagatorgi",
        "city": "107 Reykjavík",
        "phone": "530-1919",
        "image": "http://kvikmyndir.is/images/biohus_biosida/haskolabio.jpg",
        "description": "Í Háskólabíó eru 7 misstórir fyrirlestrarsalir sérhannaðir fyrir fundi og fyrirlestra, sá minnsti 23 sæta og sá stærsti 970 sæta, samtals 1891 sæti.\n\nÍ öllum sölunum eru þægilegir stólar, í sumum felliborð og hallandi gólf og veitir það þátttakendum bestu aðstæður til að fylgjast með fyrirlesurum og myndefni á tjaldi. Auk þess er möguleiki á að bæta við fundaaðstöðu í öðrum byggingum Háskólans á svæðinu.\n\nGott aðgengi er fyrir fatlaða í öllu húsinu. 700 bílastæði eru umhverfis húsið.\n\n<br><br><b>\n\nVerð á bíómiðum</b>:<br>\nAlmennt: 1100kr<br>\nÖryrkjar og eldriborgarar: 800kr<br>\nBörn yngri en 8 ára: 600kr<br>\nTilbiðsbíó um helgar: 550kr (valdar sýningar)<br>\nGræna Ljósið almennt verð: 1200kr<br>\nGræna Ljósið öryrkjar og eldriborgarar: 900kr<br>\nGræna Ljósið barnamiði 8 ára og yngri: 650kr<br>\nGræna Ljósið tilboðsbíó um helgar: 550kr (valdar sýningar)<br>\nÞriðjudagstilboð: 500kr (allar myndir)<br>\n",
    },
    {
        "id": 3,
        "name": "Borgarbíó",
        "website": "http://www.borgarbio.is",
        "location": "Hólabraut 12",
        "city": "600 Akureyri",
        "phone": "462-2602",
        "image": "http://kvikmyndir.is/images/biohus_biosida/borgarbio.jpg",
        "description": "Borgarbíó Akureyri er búið 2 kvikmyndasölum og tekur rúmlega 300 manns í sæti, en við það vinnur á annan tug manns. Kvikmyndahúsið er eitt fárra frumsýningabíóa utan höfuðborgarinnar og var stofnað fyrir miðja síðustu öld og er því líklega eitt elsta kvikmyndahús á landinu.<br><br>Kvikmyndahúsið hefur verið leiðandi meðal kvikmyndahúsa á landsbyggðinni, enda var það lengi vel eina fjölsala-kvikmyndahúsið utan Reykjavíkur og einnig það stærsta. <br><br><b>Verð á bíómiðum</b>:<br>Almennt: 1000kr<br>Midi.is: 950kr<br>Öryrkjar og eldriborgarar: 700kr<br>Börn yngri en 8 ára: 550kr<br>Íslenskar kvikmyndir: 1200kr<br>",
    },
    {
        "id": 4,
        "name": "Laugarásbíó",
        "website": "http://www.laugarasbio.is",
        "location": "Laugarási",
        "city": "104 Reykjavík",
        "phone": "553-2075",
        "image": "http://kvikmyndir.is/images/biohus_biosida/laugarasbio.jpg",
        "description": "",
    },
    {
        "id": 5,
        "name": "Bíó Paradís",
        "website": "http://bioparadis.is",
        "location": "Hverfisgötu 54",
        "city": "Reykjavík",
        "phone": '',
        "image": "http://kvikmyndir.is/images/biohus_biosida/bioparadis.jpg",
        "description": '',
    },
    {
        "id": 6,
        "name": "Álfabakki",
        "website": "http://www.sambioin.is",
        "location": "Álfabakka",
        "city": "109 Reykjavík",
        "phone": "575-8900",
        "image": "http://kvikmyndir.is/images/biohus_biosida/alfabakki.jpg",
        "description": "Sambíóin álfabakka var byggt árið 1982 og er eitt fullkomnasta kvikmyndahús landsins.\nBíóið var fyrsta kvikmyndahúsið á norðurlöndum sem var búið THX kerfinu. Sambíóin álfabakkka er í dag búið 6 kvikmyndasölum, þetta var fyrsta kvikmyndahúsið sem bauð upp á lúxus VIP sal, en sá salur er búinn þægilegum rafdrifnum sætum, sá salur var vígður í ágúst árið 2001.<br><br><b>Verð á bíómiðum</b>:<br>Almennt: 1000kr<br>Öryrkjar og eldriborgarar: 750kr<br>\nBörn 8-12 ára: 700kr<br>\nBörn 7 ára og yngri: 550kr<br>VIP salur: 2000kr<br>Kaupþing: 750kr<br><span style=\"font-style: italic;\">Midi.is: -100kr</span> <br>",
    },
    {
        "id": 7,
        "name": "Kringlubíó",
        "website": "http://www.sambioin.is",
        "location": "Kringlunni 4-6",
        "city": "103 Reykjavík",
        "phone": "575-8900",
        "image": "http://kvikmyndir.is/images/biohus_biosida/kringlan.jpg",
        "description": "Sambíóin Kringlunni var opnað árið 1996.\r\n\r\nÞað var fyrsta kvikmyndahúsið á íslandi sem bauð uppá THX hljóðkerfi í öllum sölum. Sambíóin Kringlunni er fyrsta kvikmyndahúsið á Íslandi sem býður uppá digital bíósýningar.",
    },
    {
        "id": 8,
        "name": "Sambíóin Egilshöll",
        "website": "http://www.sambio.is",
        "location": "Egilshöll",
        "city": "Reykjavík",
        "phone": "575-8900",
        "image": "http://kvikmyndir.is/images/biohus_biosida/egilsholl.jpg",
        "description": '',
    },
    {
        "id": 9,
        "name": "Sambíóin, Akureyri",
        "website": "http://www.sambioin.is",
        "location": "Ráðhústorgi 8",
        "city": "600 Akureyri",
        "phone": "461-4666",
        "image": "http://kvikmyndir.is/images/biohus_biosida/nyjabio.jpg",
        "description": "Sambíóin á Akureyri hafa yfir tveimur sýningarsölum að ráða. A salur tekur 211 manns í sæti en B salur 98 manns. Kvikmyndahúsið er glæsilega útbúið og hefur verið mikið endurnýjað frá því sem var hér á árum áður þegar Akureyringar þekktu það helst undir nafninu Nýja bíó. Húsið var reist árið 1929 og rekið undir Nafninu NýjaBío Til fjölda ára Rekstri Kvikmyndahús var síðan hætt og Síðar tók við nýr rekstur í húsinu en þá var settur á lagginar skemmtistaðurinn 1929 en þema skemmtistaðarins var allt tengt kvikmyndum og var einn vinsælasti skemmtistaður landsins í mörg ár og spiluðu það margar af stærstu hljómsveitum landsins árið 1995 brann svo húsið og öllum rekstri hætt En árið í nóvember 1998  var Bíóið opnað almenningi aftur og þá auðvitað undir nafninu Nýja bíó.\r\n",
    },
    {
        "id": 10,
        "name": "Sambíóin, Selfossi",
        "website": "http://www.sambion.is",
        "location": "Eyrarvegi 2",
        "city": "800 Selfoss",
        "phone": "575-8900",
        "image": "http://kvikmyndir.is/images/biohus_biosida/sambioinselfossi.jpg",
        "description": "Sambíóin Selfossi var opnað 11.des 2004.  Bíóið bíður upp á tvo sali, ný og þægileg sæti með gott rými fyrir fætur og góðan halla á milli sætaraða. Hljóðkerfið er í  Dolby Digital gæðum og allar þær kröfur sem THX staðallinn gerir, enda stillt með THX tækjum.\r\n\r\nUpphaflega hét bíóið Selfossbíó en Sambíóin keyptu það í ágúst 2007.",
    },
    {
        "id": 11,
        "name": "Sambíóin, Keflavík",
        "website": "http://www.sambioin.is",
        "location": "Hafnargötu 33",
        "city": "230 Keflavík",
        "phone": "421-1170",
        "image": "http://kvikmyndir.is/images/biohus_biosida/sambioinkeflavik.jpg",
        "description": "\r\nSambíóin Keflavík voru fyrsta Sambíóið , það var byggt árið 1941 af Eyjólfi Ásberg. Sambíóin keflavík er búið 2 sölum. Salur eitt var endurreistur árið 1998 og salur 2 var byggður 2001",
    }
];